GITForce/src/objects/DemoReportCard__c.object
<CustomObject>
    <fields>
        <fullName>English__c</fullName>
        <label>English</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FatherName__c</fullName>
        <label>FatherName</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gsection__c</fullName>
        <label>Gsection</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hindi__c</fullName>
        <label>Hindi</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StudentName__c</fullName>
        <label>StudentName</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telugu__c</fullName>
        <label>Telugu</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <formula>English__c  +  Hindi__c  +  Telugu__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>DemoReportCard</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>DemoReportCardNo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DemoReportCards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GITForce/src/classes/DemoReportCard.cls
public class DemoReportCard 
    {
    public list<DemoReportCard__c> lstcard{get;set;}
    public String m_Gsection { get; set; }
    public string m_StudentName{get;set;}
    public string m_FatherName{get;set;}
    public string m_Telugu{get;set;}
    public string m_Hindi{get;set;}
    public string m_English{get;set;}
    public string m_Total{get;set;}
    public string searchString{get;set;}
    //public string grade{get;set;}
    
    public pageReference search() 
    {
    lstcard=[SELECT StudentName__c,Gsection__c,FatherName__c,Telugu__c,Hindi__c,English__c,Total__c from DemoReportCard__c WHERE Gsection__c =: m_Gsection ];
    //lstcard= 'SELECT  StudentName__c,Gsection__c,Total__c FROM DemoReportCard__c' + 'WHERE m_StudentName LIKE  \'%'+searchString+'%\' ORDER BY StudentName__c  ';

     //System.debug('***'+lstcard + '***'+ m_Gsection ); 
    return null;
    }
    /*
    public List<SelectOption> getGsections()
    {
    List<SelectOption> options=new List<SelectOption>();
    List<DemoReportCard__c> Gsectionlist=new List<DemoReportCard__c>();
    Gsectionlist=[SELECT Gsection__c from DemoReportCard__c];
    options.add(new selectOption('--None--','--None--'));
    
    for(Integer j=0;j<Gsectionlist.size();j++)
    {
      options.add(new SelectOption(Gsectionlist[j].Gsection__c ,Gsectionlist[j].Gsection__c ));
    }   
    return options;
    }*/
    }