GITForce/src/objects/tblStudent__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <picklist>
            <picklistValues>
                <fullName>Hyderabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vishakapatnam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jeypore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Koraput</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhuwaneshwar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Raivellore</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FatherName__c</fullName>
        <label>FatherName</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GFatherName__c</fullName>
        <label>GFatherName</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>HouseNo__c</fullName>
        <label>HouseNo</label>
        <length>16</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Nationality__c</fullName>
        <label>Nationality</label>
        <picklist>
            <picklistValues>
                <fullName>INDIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUSTRALIAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMERICAN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>20</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <required>true</required>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>Andhra Pradesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Orissa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Madhya Pradesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tamil Nadu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delhi</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StudStatus__c</fullName>
        <defaultValue>false</defaultValue>
        <label>StudStatus</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>StudentName__c</fullName>
        <label>StudentName</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telephone__c</fullName>
        <label>Telephone</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <label>tblStudent</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>tblStudents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GITForce/src/classes/StudentRegistration.cls
public Class StudentRegistration
{

  public String  m_StudID{get;set;}
  public String  m_studentName{get;set;}
  public tblStudent__c m_Password{get;set;}
  public String m_FatherName{get;set;}
  public String m_GFatherName{get;set;}
  public boolean m_StudStatus{get;set;}
  public tblStudent__c m_DOB{get;set;}
  public tblStudent__c m_Telephone{get;set;}
  public tblStudent__c  m_HouseNo{get;set;}
  public String  m_State{get;set;}
  public String  m_City{get;set;}
  public String  m_Nationality{get;set;}
  public String  m_Gender{get;set;}
    
    
  public StudentRegistration()
  {
  m_Telephone=new tblStudent__c();
  m_HouseNo= new tblStudent__c(); 
  m_DOB=new tblStudent__c(); 
  m_Password= new tblStudent__c(); 
  }
  
  public void InsertNewRecord()
  {
      tblStudent__c objStud =new tblStudent__c();

      //objStud.StudID__c=m_StudID;     
      objStud.StudentName__c=m_StudentName;
      //objStud.Password__c=m_Password;
      String t=m_Password.Password__c;
      objStud.FatherName__c=m_FatherName;
      objStud.GFatherName__c=m_GFatherName;
      objStud.StudStatus__c=m_StudStatus;
      Date d1=m_DOB.DOB__c;
      //objStud.Telephone__c=m_Telephone;
      String hn=m_HouseNo.HouseNo__c;
      //objStud.HouseNo__c =m_HouseNo;
      String i=String.valueOf(m_Telephone.Telephone__c);
      objStud.Nationality__c=m_Nationality;
      objStud.State__c=m_State;
      objStud.City__c=m_City;
      objStud.Gender__c=m_Gender;
            
      try
      {
      insert objStud;
      }
      catch(Exception exc)
      {
      System.debug('###'+exc);
      ApexPages.Message myMsg =new ApexPages.Message(ApexPages.Severity.info,'Registration Success');
      }
   
  }
  

}