GITForce/src/objects/tblStudent__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <picklist>
            <picklistValues>
                <fullName>Hyderabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vishakapatnam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jeypore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Koraput</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhuwaneshwar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Raivellore</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FatherName__c</fullName>
        <label>FatherName</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GFatherName__c</fullName>
        <label>GFatherName</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>HouseNo__c</fullName>
        <label>HouseNo</label>
        <length>16</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Nationality__c</fullName>
        <label>Nationality</label>
        <picklist>
            <picklistValues>
                <fullName>INDIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUSTRALIAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMERICAN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>Andhra Pradesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Orissa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Madhya Pradesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tamil Nadu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delhi</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StudStatus__c</fullName>
        <defaultValue>false</defaultValue>
        <label>StudStatus</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>StudentName__c</fullName>
        <label>StudentName</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telephone__c</fullName>
        <label>Telephone</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <label>tblStudent</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>tblStudents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GITForce/src/classes/EditStudent.cls
public class EditStudent
{
    public list<StudentWrapper> wraperlist=new list<StudentWrapper>();
    
    public class StudentWrapper
    {
    
    
     // public List<tblStudent__c> lstStud{get;set;}
     // public tblStudent__c objStu{get;set;} 
      public Id Id{get;set;}
      public String  m_StudentName{get;set;}
      public String m_FatherName{get;set;}
      public String m_GFatherName{get;set;}
      public Date m_DOB{get;set;}
      public String  m_HouseNo{get;set;}
      public String  m_State{get;set;}
      public String  m_City{get;set;}
      public String  m_Nationality{get;set;}
      public String m_Gender{get;set;}
      public boolean m_StudStatus{get;set;}
      public String m_Telephone{get;set;}
       
        public boolean m_EditMode{get;set;}
        public boolean m_TextMode{get;set;}
        
       
    }
    
     public EditStudent()
    {
    
        
         for(tblStudent__c objStud:[select Id,StudentName__c,FatherName__c,GFatherName__c,
                    DOB__c,Gender__c,HouseNo__c ,State__c,StudStatus__c,
                    City__c,Nationality__c,Telephone__c from  tblStudent__c  ])
        {
            StudentWrapper sw=new StudentWrapper();
            sw.Id=objStud.Id;
            sw.m_StudentName=objStud.StudentName__c;
            sw.m_FatherName=objStud.FatherName__c;
            sw.m_GFatherName=objStud.GFatherName__c;
            sw.m_HouseNo=objStud.HouseNo__c;
            sw.m_Telephone=objStud.Telephone__c;
            sw.m_State=objStud.State__c;
            sw.m_City=objStud.City__c;
            sw.m_Nationality=objStud.Nationality__c;
            sw.m_StudStatus=false;
            sw.m_EditMode=false;
            sw.m_TextMode=true;
            wraperlist.add(sw);
            
        }
        
        
    }
       
    public list<StudentWrapper> getStudent()
    {
        return wraperlist;
    }
    public void editStudent()
    {
        String sid=apexpages.currentPage().getParameters().get('empid');
        system.debug('eid::::::::::'+sid);
        for(StudentWrapper objSW:wraperlist)
        {
            system.debug('objEw.Id:::::::::'+objSW.Id);
            if(objSW.Id==sid)
            {
                objSW.m_EditMode=true;
                objSW.m_TextMode=false;
            }
            
        }
      }  
    
   /* 
    public void update1()
    {
    for(tblStudent__c objStu :[SELECT Id,StudentName__c,FatherName__c,GFatherName__c,
                    DOB__c,Gender__c,HouseNo__c ,State__c,StudStatus__c,
                    City__c,Nationality__c,Telephone__c from  tblStudent__c ]);
         {
         StudentWrapper sw=new StudentWrapper();
                                
    sw.Id=objStu.Id;                
    sw.m_StudentName=objStu.StudentName__c;                
    sw.m_FatherName=objStu.FatherName__c;
    sw.m_GFatherName=objStu.GFatherName__c;
    /*objStu.DOB__c=m_DOB;
    objStu.Gender__c=m_Gender;
    objStu.HouseNo__c=m_HouseNo;
    objStu.Nationality__c=m_Nationality;
    objStu.State__c=m_State;
    objStu.City__c=m_City;
    objStu.StudStatus=m_StudStatus;
    objStu.Telephone=m_Telephone;
    
    wraperlist.add(sw);
    }
  }
 */
 }