GITForce/src/objects/tblUser__c.object
<CustomObject>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <referenceTo>tblStudent__c</referenceTo>
        <relationshipLabel>tblUsers</relationshipLabel>
        <relationshipName>tblUsers_tblStudents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>tblUser</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>UserID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>tblUsers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GITForce/src/classes/tblUser.cls
public class tblUser {

     public PageReference clear() {
    PageReference clearpage=new PageReference('/apex/tblUser');
        return clearpage;
    }



    public PageReference register() {
        return null;
    }

PageReference newPage;

    public PageReference tblUser() {
    
    newPage = Page.tblStudent;
    return newPage.setRedirect(true);

    
        return null;
    }


    public String m_Password { get; set; }

    public String m_Username { get; set; }
   
    public tblUser()
    
    {
    
    }
    public void login()

    {
    list<tblUser__c> lstuser = new list<tblUser__c>();
      lstuser =[select  Password__c  from tblUser__c];
      
      if((lstuser.size())== 1)
      {
         ApexPages.Message myMsg =new ApexPages.Message(ApexPages.Severity.info,'Login Success');

                  ApexPages.addMessage(myMsg);
          newPage = Page.tblStudent;

          
      }
      
}
}